name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: oracle-actions/setup-java@v1
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION_GA }}
        with:
          website: ${{ vars.JDK_SRC }}
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - run: |
          printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
          java --version
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION_GA }}

      - uses: oracle-actions/setup-java@v1
        with:
          website: ${{ vars.JDK_SRC }}
          release: ${{ vars.JAVA_VERSION_GA }}

      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
        if: ${{ vars.GRADLE_JAVA_VERSION == vars.JAVA_VERSION_GA }}

      - name: Github Packages
        run: |
          printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties
          java --version
          ./gradlew --stacktrace --no-daemon -PjavaVersion=${{ vars.JAVA_VERSION_GA }} -Pversion=${{ github.ref_name }} check :core:publish :jetty:publish :solana:publish
        env:
          VIRTUAL_SERVER: true
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
